### ISSUE TITLE
Práctica 8 

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-entrevista_gestion-de-proyecto#1]
[PRACTICA8 roadmap.pdf](https://github.com/user-attachments/files/17532706/PRACTICA8.roadmap.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by josealfredo79** [comment]
En tu repositorio falta un pull request...y asi mismo una incidencia de que estas haciendo esa actividad y no puedo evaluar...si no esta esa actividad por favor

**Comment by ferh1235** [comment]
https://github.com/SistemasTecTlaxiaco/MejorandoelCampo/pull/4

**Comment by josealfredo79** [comment]
Calificacion 18
