### ISSUE TITLE
Pratica 10

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-entrevista_gestion-de-proyecto#2]
[Prtica 10.pdf](https://github.com/user-attachments/files/18101965/Prtica.10.pdf)

**Comment by carlos0716c** [comment]
Portada y escudos institucionales: 25 puntos
Descripción detallada del procedimiento: 25 puntos
Incluye ilustraciones: 25 puntos
Resultado y conclusión: 25 puntos
Porcentaje obtenido 100% = 50 puntos

**Comment by josealfredo79** [comment]
bien hecho y revisado...
